#!/bin/sh
#
# Stats32 script generate some system infos for the motd file.
# Date: 08/2017
# 
#  _______ __          __          ______ ______
# |     __|  |_.---.-.|  |_.-----.|__    |__    |
# |__     |   _|  _  ||   _|__ --||__    |    __|
# |_______|____|___._||____|_____||______|______|
#
#     by    Ｅｒｒｅｕｒ３２
#

## need figlet (auto installing with the ./install.sh)
# figlet -f wideterm

figlet -f chunky $(hostname)

echo -e "\033[0m"
[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf  "\033[5m%s (%s).\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
echo -e "\e[0mKernel Info:   \033[5m   " `uname -smr`;
echo -e "Shell: $SHELL \e[0m"
echo -e 'Last SSH:\e[1;30m'; last -a | grep pts |  head -3
echo -e  "\e[0m"

load=`cat /proc/loadavg | awk '{print $1}'`
root_usage=`df -h / | awk '/\// {print $(NF-1)}'`
memory_usage=`free -m | awk '/Mem:/ { total=$2 } /buffers\/cache/ { used=$3 } END { printf("%3.1f%%", used/total*100)}'`
swap_usage=`free -m | awk '/Swap/ { printf("%3.1f%%", "exit !$2;$3/$2*100") }'`
users=`users | wc -w`
time=`uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }'`
processes=`ps aux | wc -l`
ip=`hostname -i`
# if IP  fail try this 
# ip=`hostname -i | awk '{ printf $2 }'`

printf "%s-----------\t---\t------------\t----------\n"
printf "System load :\t%s\tIP Address:\t%s\n" $load $ip 
printf "Memory usage:\t%s\tSystem uptime:\t%s\n" $memory_usage "$time"
printf "Usage on /  :\t%s\tSwap usage:\t%s\n" $root_usage $swap_usage
printf "Local Users :\t%s\tProcesses:\t%s\n" $users $processes
printf "%s-----------\t---\t------------\t----------\n"
echo -e "\n\e[93m Ｇｅｎｅｒａｔｅｄ  ｂｙ  ＭＯＴＤｓ３２\e[0m"
